# fly.toml app configuration file generated for manalath on 2026-09-18T09:26:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'manalath'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'
  max_unavailable = 1.0

[env]
  DB_PATH = '/data/manalath.sqlite'
  PORT = '8080'
  PUBLIC_URL = 'https://manalath.top'

[[mounts]]
  source = 'manalath_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/xrpc/_health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
