// Hand-written barrel over the generated lexicon code (packages/shared/src/lexicon is
// regenerated by `bun run lex`; do not edit it).
export { ids, lexicons, schemas, validate } from './lexicon/lexicons.js';
export * as Match from './lexicon/types/top/manalath/match.js';
export * as Accept from './lexicon/types/top/manalath/accept.js';
export * as Move from './lexicon/types/top/manalath/move.js';
export * as Defs from './lexicon/types/top/manalath/defs.js';
export * as StrongRef from './lexicon/types/com/atproto/repo/strongRef.js';
